on: [push]

name: CI

jobs:
  build:
    name: FixNameCase project
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Archive built files
        uses: actions/upload-artifact@v2
        with:
          name: Built binaries
          path: |
            target/release/fix-name-case
            target/release/fix-name-case.exe
